- pages/index.tsx
display button according to login state
> fix button on homepage

- pages/dashboard/project/[projectId].tsx
Tested **cusdis** and found this minor issue.
> Adds closing /div to embed codesnippet avoiding layout issues

- public/doc/advanced/sdk.md
Awesome project, just noticed a spelling mistake in the sdk integration documentation.
> Fix spelling mistake

- pages/dashboard/index.tsx
Similar to `Add Website` button and with hover.
> dashboard ui enhancement

- widget/lang/es.js
Create `es.js` in widget lang to support es language.
> Add es lang to i18n

- public/doc/advanced/i18n.md
- public/doc/index.html
- widget/i18n.js
- widget/lang/es.js
- widget/lang/zh-cn.js
first of all, let me thank U 🙇‍♂️, the repo is so awesome and light-weight, and I already integrated it into my personal blog with fewer options!
and found there has a typo of **cusdis**, Cusdis is true, Cusdis is awesome! ❤️ 🥳
> fix: cusdis word typo

- public/doc/advanced/i18n.md
- widget/lang/tr.js
🌐 Translate to tr (Turkish translate)
> 🌐 Translate to tr

- public/doc/features/notification.md
> Add examples of configuration SMTP services

- public/doc/_sidebar.md
- public/doc/self-host/manual.md
- utils.server.ts
Load .env files in the project root to ease the steps. The env will be loaded by Prisma as well.
Close #93
> Add doc for Manual install

- pages/api/open/comments.ts
- pages/api/project/[projectId]/comments.ts
- service/comment.service.ts
- utils.client.ts
- widget/Widget.svelte
> add timezone offset (fix #100)

- widget/lang/fr.js
Hi !
I added Cusdis to my [blog](https://www.maxvdw.ovh/) and I thought I mistranslated some stuff :innocent: . Here are the fixes.
> Update French locale

- widget/lang/ca.js
- widget/lang/es.js
Correct some typos in line 19 of `es.js` and create `ca.js` (Catalan).
> Update es.js and create ca.js (Catalan)

- widget/lang/ja.js
> Create ja.js (Japanese)

- widget/lang/tr.js
"Nickname" and "email" was in English, also changed the translation of "powered by cusdis" to make sense.
> Update Turkish translation

- public/doc/self-host/railway.md
This PR adds a guide to host Cusdis on Railway.
> add hosting guide for railway

- public/doc/advanced/i18n.md
- widget/lang/nl.js
New user of Cusdis and loving it already. Here is my first contribution adding my local language. Looking to contribute more!
> Added dutch langauge

- widget/components/Reply.svelte
Fixes https://github.com/djyde/cusdis/issues/198
https://user-images.githubusercontent.com/47485431/162788035-f706d2d5-9a09-4a7a-b906-8c441c72d33e.mov
> Responsive form

- widget/lang/zh-cn.js
- widget/lang/zh-tw.js
> fix: ellipsis display in Chinese

- .github/workflows/ci.yml
- Dockerfile
- yarn.lock
Related to this PR: https://github.com/djyde/cusdis/pull/206
> Optimize Dockerfile to reduce image size(master branch)

- public/doc/advanced/i18n.md
- widget/lang/ar.js
Also added Arabic to the list of supported languages in docs.
> Fixed Arabic translation

- widget/lang/cs.js
Strings for czech language ('cs̈́' of [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1))
> Added czech language

- widget/lang/de.js
Hey, just a quick addition to the languages.
> feat(lang): add german translation

- public/doc/_sidebar.md
- public/doc/features/moderation.md
- Adding missing pages to menu
- Re-arranging a menu item
- Foxing broken image
Revives the current PRs, which I accidentally closed:
- https://github.com/djyde/cusdis/pull/220
- https://github.com/djyde/cusdis/pull/219
> Fixing Docs Menu and Missing Pages

- components/Layout.tsx
- components/Navbar.tsx
- config.common.ts
- pages/api/comment/[commentId]/approve.ts
- pages/api/open/approve.ts
- pages/api/projects.ts
- pages/api/subscription.ts
- pages/dashboard/project/[projectId].tsx
- pages/getting-start.tsx
- pages/index.tsx
- pages/open/approve.tsx
- prisma/pgsql/migrations/20230713082802_subscription/migration.sql
- prisma/pgsql/schema.prisma
- prisma/sqlite/migrations/20230713042856_subscription/migration.sql
- prisma/sqlite/migrations/20230713055831_subscription/migration.sql
- prisma/sqlite/migrations/20230713070441_usage/migration.sql
- prisma/sqlite/schema.prisma
- service/subscription.service.ts
- service/usage.service.ts
- service/viewData.service.ts
- service/webhook.service.ts
- utils.server.ts
This PR includes Cusdis Cloud, powered by Lemon Squeezy.
> Subscription

- widget/lang/th.js
Hi~ I want to add Thai language so here this pull request.
> add Thai language
